apiVersion: apps/v1
kind: Deployment
metadata:
  name: homecare-hub
  namespace: digital-twin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homecare-hub
  template:
    metadata:
      labels:
        app: homecare-hub
    spec:
      imagePullSecrets:
        - name: <secret>
      containers:
        - name: homecare-hub
          image: stevenlarry473/homecare-hub:latest
          imagePullPolicy: "Always"
          ports:
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: homecare-hub-configmap
