apiVersion: v1
kind: Service
metadata:
  name: homecare-hub
  namespace: digital-twin
spec:
  type: NodePort
  ports:
    - name: homecare-hub
      port: 9000
      targetPort: 9000
      nodePort: 9000
      protocol: TCP
  selector:
    app: homecare-hub
