apiVersion: v1
kind: ConfigMap
metadata:
  name: modeling-configmap
  namespace: digital-twin
  labels:
    app: modeling
data:
  SCH_SERVICE_NAME: http://sif-edge.digital-twin:9000
  INFLUX_TOKEN: 0NxTXKuB4iDmWJn0_FzwwQ45ZxZfpnDEQWAQItqHjx-rurBqwE8afYIRPwG2isnynumGim1FxdRyuSmqeEsQdg==
  INFLUX_URL: http://192.168.0.103:8086
  MINIO_URL: 192.168.0.103:9090
  MINIO_ACCESSKEY: bSYIFuEHZa3JHTKg6WE9
  MINIO_SECRETKEY: u8TnjmYYEcUJNugWSOUZwXEDqu2FU2JToOIAx2Lt

