apiVersion: apps/v1
kind: Deployment
metadata:
  name: modeling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modeling
  template:
    metadata:
      labels:
        app: modeling
    spec:
      #imagePullSecrets:         # This field is useful in case your image resides in a private registry
      #  - name: <secret-name>   # you can remove this block if you are user Docker Hub
      containers:
        - name: modeling
          image: stevenlarry473/modeling:latest   # If you do not provide a <tag>, k8s will use `latest`
          imagePullPolicy: "Always"   # This means the container runtime will pull the image every time the pod is (re-)created. Another possible value is 'IfNotPresent'
          ports:
            - containerPort: 8000     # Exposes a port in a given container to receive traffic
          envFrom:
            - configMapRef:
                name: modeling-configmap
